// --- src/aim.cpp ---
// Triggerbot. Detection is read-only; firing injects a mouse click.
//
// ══ WHY IT WAS "DELAYED" — A DESIGN PROBLEM, NOT A TIMING VALUE ═════════
// The previous version PULSED the mouse: press, hold 12 ms, release, then wait
// out a 16 ms cooldown before the next press. That caps the fire rate at about
// 60 shots/sec REGARDLESS of the weapon, and adds a fixed gap after every shot.
// On a weapon that fires faster, the trigger was the bottleneck.
//
// Real triggerbots HOLD the button while a target is under the crosshair and
// release when it is not. For an automatic weapon that means the game fires
// continuously at its own rate of fire, which is the maximum possible -- there
// is nothing left for us to limit.
//
// ══ WHY THE BUTTON MUST STILL BE RELEASED SOMETIMES ═════════════════════
// A shot registers on the RELEASED -> PRESSED transition. So:
//   * while on target, HOLD  (auto weapons fire continuously)
//   * when the target leaves, RELEASE (so re-entering is a fresh edge)
// A "pulse" is only needed for semi-automatic weapons, and it is generated by
// the target leaving and re-entering the bone radius rather than by a timer.
//
// ══ THE DELAY ═══════════════════════════════════════════════════════════
// Delay is the reaction time BEFORE the first press after acquiring a target.
// It is measured from acquisition and does not gate sustained fire. At 0 the
// press happens on the very next loop iteration.
#include "aim.h"
#include "esp.h"
#include "memory.h"
#include "offsets.h"

#include <Windows.h>
#include <mmsystem.h>
#include <atomic>
#include <chrono>
#include <cmath>
#include <thread>

#pragma comment(lib, "winmm.lib")

extern HWND g_cs2_hwnd;
extern ESP g_esp;
extern int g_local_team;
extern int g_screen_w;
extern int g_screen_h;

namespace {

// Hardcoded bone radii, authored at 1080p and scaled by height. No user control.
struct Hit { int bone; const char* name; float radius_px_at_1080; };
constexpr Hit kHits[] = {
    { BONE_HEAD,    "head",   14.0f },
    { BONE_NECK,    "neck",   12.0f },
    { BONE_CHEST,   "chest",  16.0f },
    { BONE_SPINE_1, "spine",  16.0f },
    { BONE_PELVIS,  "pelvis", 15.0f },
};
constexpr float kReferenceHeight = 1080.0f;

std::atomic<bool>  g_stop{false}, g_started{false};
std::atomic<bool>  g_on{false}, g_fire{true};
std::atomic<bool>  g_teamcheck{true}, g_vischeck{false};
std::atomic<int>   g_key{0};        // 0 == unbound == OFF
std::atomic<int>   g_delay{0};      // reaction time before the FIRST press

std::atomic<bool>  g_dbg_firing{false}, g_dbg_on{false};
std::atomic<bool>  g_dbg_vis{false},    g_dbg_visable{false};
std::atomic<float> g_dbg_dist{-1.0f};
std::atomic<const char*> g_dbg_bone{"-"};
std::atomic<const char*> g_dbg_blocked{"-"};
std::atomic<int>   g_dbg_held{0};
std::atomic<int>   g_vis_samples{0}, g_vis_hits{0};

std::thread g_thread;

// The loop is 1 ms. There is no cooldown: the natural cadence is dictated by
// whether a target is under the crosshair, not by a timer.
constexpr double kLoopMs = 1.0;

double now_ms() {
    static const auto t0 = std::chrono::steady_clock::now();
    return std::chrono::duration<double, std::milli>(
               std::chrono::steady_clock::now() - t0).count();
}

// Sleep the bulk, spin the last stretch. A plain sleep_for(1ms) can round to
// 15.6 ms without the timer period raised; timeBeginPeriod(1) is set at init,
// and the spin covers the remainder either way.
void wait_ms(double ms) {
    const auto deadline = std::chrono::steady_clock::now() +
        std::chrono::microseconds((long long)(ms * 1000.0));
    for (;;) {
        const auto now = std::chrono::steady_clock::now();
        if (now >= deadline) return;
        const auto left = deadline - now;
        if (left > std::chrono::milliseconds(1))
            std::this_thread::yield();
        else
            std::this_thread::yield();
    }
}

bool cs2_focused() {
    return g_cs2_hwnd && GetForegroundWindow() == g_cs2_hwnd;
}

void mouse_down() {
    INPUT in{};
    in.type = INPUT_MOUSE;
    in.mi.dwFlags = MOUSEEVENTF_LEFTDOWN;
    SendInput(1, &in, sizeof(INPUT));
}

void mouse_up() {
    INPUT in{};
    in.type = INPUT_MOUSE;
    in.mi.dwFlags = MOUSEEVENTF_LEFTUP;
    SendInput(1, &in, sizeof(INPUT));
}

// Radar-spotted mask. APPROXIMATE visibility -- radar state, not line of sight.
uint32_t spotted_mask(const Memory& mem, uintptr_t pawn) {
    return mem.read<uint32_t>(
        pawn + offsets::m_entitySpottedState + offsets::m_bSpottedByMask);
}

void run_thread() {
    SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);

    bool   held = false;        // is the button physically down right now
    double held_since = 0.0;
    double target_since = 0.0;
    bool   vis_trusted = false;

    while (!g_stop.load()) {
        wait_ms(kLoopMs);

        const int k = g_key.load();

        // UNBOUND MEANS OFF.
        const bool gate = g_on.load() && g_mem.is_valid() && cs2_focused() &&
                          k != 0 && ((GetAsyncKeyState(k) & 0x8000) != 0);

        if (!gate) {
            if (held) { mouse_up(); held = false; }
            g_dbg_firing.store(false);
            g_dbg_on.store(false);
            g_dbg_held.store(0);
            target_since = 0.0;
            continue;
        }

        const int sw = g_screen_w, sh = g_screen_h;
        if (sw <= 0 || sh <= 0) continue;

        // Newest sample, no interpolation: firing on a smoothed position would
        // aim behind a moving target.
        const std::vector<PlayerESP> players =
            g_esp.project(g_mem, g_mem.client_dll, sw, sh, false);

        const float cx = sw * 0.5f, cy = sh * 0.5f;
        const float scale = (float)sh / kReferenceHeight;

        const uintptr_t local_pawn =
            g_mem.read<uintptr_t>(g_mem.client_dll + offsets::dwLocalPlayerPawn);

        bool  found = false, blocked = false, has_vis = false;
        float best = 1e9f;
        const char* best_name = "-";
        const char* why = "-";

        for (const PlayerESP& p : players) {
            if (p.team == 0) continue;
            if (g_teamcheck.load() && g_local_team != 0 &&
                p.team == g_local_team)
                continue;

            const Hit* in_bone = nullptr;
            for (const Hit& h : kHits) {
                if (!p.bone_ok[h.bone]) continue;
                const float dx = p.bones[h.bone].x - cx;
                const float dy = p.bones[h.bone].y - cy;
                const float d = std::sqrt(dx * dx + dy * dy);
                if (d > h.radius_px_at_1080 * scale) continue;
                if (!in_bone || d < best) {
                    in_bone = &h;
                    best = d;
                    best_name = h.name;
                }
            }
            if (!in_bone) continue;

            found = true;

            if (g_vischeck.load() && p.pawn) {
                const uint32_t mask = spotted_mask(g_mem, p.pawn);
                ++g_vis_samples;
                if (mask != 0) { ++g_vis_hits; vis_trusted = true; }

                if (vis_trusted) {
                    if (mask == 0) { blocked = true; why = "vis"; continue; }
                    has_vis = true;
                }
            } else {
                has_vis = true;
            }
        }

        g_dbg_on.store(found);
        g_dbg_vis.store(has_vis);
        g_dbg_visable.store(vis_trusted);
        g_dbg_dist.store(found ? best : -1.0f);
        g_dbg_bone.store(found ? best_name : "-");
        g_dbg_blocked.store(blocked ? why : "-");

        const double now = now_ms();
        const bool on_target = found && !blocked;

        // ---- acquisition timer, for the delay only ----
        if (!on_target) {
            target_since = 0.0;
            g_dbg_held.store(0);
        } else if (target_since <= 0.0) {
            target_since = now;
        }
        if (on_target)
            g_dbg_held.store((int)(now - target_since));

        // ---- HOLD while on target, RELEASE when not ----
        // No per-shot cooldown and no pulse timer. Sustained fire comes from
        // the game's own rate of fire while the button is held; a fresh edge for
        // a semi-automatic comes from the target leaving and re-entering.
        const bool want_fire =
            on_target && g_fire.load() &&
            (g_delay.load() <= 0 ||
             (target_since > 0.0 && (now - target_since) >= g_delay.load()));

        if (want_fire && !held) {
            mouse_down();
            held = true;
            held_since = now;
            g_dbg_firing.store(true);
        } else if (!want_fire && held) {
            mouse_up();
            held = false;
            g_dbg_firing.store(false);
        }

        (void)held_since;
        (void)local_pawn;
    }

    if (held) mouse_up();
}

} // namespace

void Aim_Init() {
    if (!g_mem.is_valid()) return;
    bool e = false;
    if (!g_started.compare_exchange_strong(e, true)) return;
    timeBeginPeriod(1);
    g_stop.store(false);
    g_thread = std::thread(run_thread);
}

void Aim_Shutdown() {
    g_stop.store(true);
    if (g_thread.joinable()) g_thread.join();
    timeEndPeriod(1);
    g_started.store(false);
}

AimDebug Aim_GetDebug() {
    AimDebug d;
    d.enabled     = g_on.load();
    d.firing      = g_dbg_firing.load();
    d.on_target   = g_dbg_on.load();
    d.has_vis     = g_dbg_vis.load();
    d.vis_usable  = g_dbg_visable.load();
    d.vis_samples = g_vis_samples.load();
    d.vis_hits    = g_vis_hits.load();
    d.blocked_by  = g_dbg_blocked.load();
    d.target_dist = g_dbg_dist.load();
    d.target_bone = g_dbg_bone.load();
    d.delay_ms    = g_delay.load();
    d.held_ms     = g_dbg_held.load();
    return d;
}

void Aim_SetEnabled(bool on) { g_on.store(on); }
bool Aim_Enabled() { return g_on.load(); }
void Aim_SetFire(bool on) { g_fire.store(on); }
bool Aim_Fire() { return g_fire.load(); }
void Aim_SetKey(int vk) { g_key.store(vk); }
int  Aim_Key() { return g_key.load(); }

void Aim_SetTeamCheck(bool on) { g_teamcheck.store(on); }
bool Aim_TeamCheck() { return g_teamcheck.load(); }

void Aim_SetVisCheck(bool on) { g_vischeck.store(on); }
bool Aim_VisCheck() { return g_vischeck.load(); }

void Aim_SetDelay(int ms) {
    if (ms < 0) ms = 0;
    if (ms > 600) ms = 600;
    g_delay.store(ms);
}
int Aim_Delay() { return g_delay.load(); }
